server:
  port: 8081

topic:
  name: "t.scheduled"

spring:
  kafka:
    consumer:
      group-id: "default"
    bootstrap-servers: "localhost:9092"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: eco_webdealing_docs
    password: eco_webdealing_docs_psw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
